// Generated by Gemini 3.1 Pro.
angular.module('colorPicker', [])
.component('colorPicker', {
    bindings: {
        color: '<',      // Two-way binding for the Hex color string (e.g., '#ff0000')
        opacity: '<',    // Two-way binding for Opacity (0 to 1)
        isOpen: '<',     // Boolean to toggle the popup visibility
        updateColor: '&',   // Callback function when color changes
        onClose: '&'     // Callback function when closed
    },
    templateUrl: 'color-picker.html', // Or use an inline template string
    controller: function($element, $timeout) {
        var $ctrl = this;
        
        $ctrl.paletteWidth = 250;
        $ctrl.paletteHeight = 150;
        $ctrl.knobX = 0;
        $ctrl.knobY = 0;

        $ctrl.displayedColorHex = '';
        
        $ctrl.presets = [
            '#ff0000', '#00ff00', '#0000ff', '#ffff00', 
            '#00ffff', '#ff00ff', '#ffffff', '#000000',
            '#888888', '#ff8800'
        ];

        $ctrl.$onInit = function() {
            // Set defaults if not provided
            if (!$ctrl.color) { 
                $ctrl.color = '#ff0000'; 
                $ctrl.displayedColorHex = '#ff0000ff';
            }
            if (typeof $ctrl.opacity === 'undefined') $ctrl.opacity = 1;
            $ctrl.displayedColorHex = $ctrl.color + Math.round($ctrl.opacity * 255).toString(16).padStart(2, '0');
            $ctrl.updateFromHex();
        };

        $ctrl.$onChanges = function(changes) {
            if (changes.color && !changes.color.isFirstChange()) {
                $ctrl.displayedColorHex = $ctrl.color + Math.round($ctrl.opacity * 255).toString(16).padStart(2, '0');
                $ctrl.updateFromHex();
            }
            if (changes.opacity && !changes.opacity.isFirstChange()) {
                $ctrl.updateHexFromOpacity();
            }
        };

        // Standard HSL to Hex formula
        function hslToHex(h, s, l) {
            l /= 100;
            var a = s * Math.min(l, 1 - l) / 100;
            var f = function(n) {
                var k = (n + h / 30) % 12;
                var color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
                return Math.round(255 * color).toString(16).padStart(2, '0');
            };
            return '#' + f(0) + f(8) + f(4);
        }

        // Standard Hex to HSL formula
        function hexToHsl(hex) {
            var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
            if (!result) return { h: 0, s: 0, l: 50 };
            
            var r = parseInt(result[1], 16) / 255,
                g = parseInt(result[2], 16) / 255,
                b = parseInt(result[3], 16) / 255;
                
            var max = Math.max(r, g, b), min = Math.min(r, g, b);
            var h, s, l = (max + min) / 2;

            if (max == min) {
                h = s = 0; // achromatic
            } else {
                var d = max - min;
                s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
                switch (max) {
                    case r: h = (g - b) / d + (g < b ? 6 : 0); break;
                    case g: h = (b - r) / d + 2; break;
                    case b: h = (r - g) / d + 4; break;
                }
                h /= 6;
            }
            return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
        }

        // Called when user clicks/drags on the color palette
        $ctrl.pickColor = function(event) {
            // Use getBoundingClientRect to avoid target issues if clicking exactly on the knob
            var rect = event.currentTarget.getBoundingClientRect();
            var x = Math.max(0, Math.min(event.clientX - rect.left, rect.width));
            var y = Math.max(0, Math.min(event.clientY - rect.top, rect.height));

            $ctrl.knobX = x;
            $ctrl.knobY = y;

            // X axis = Hue (0-360)
            // Y axis = Saturation (100-0)
            var h = (x / rect.width) * 360;
            var s = 100 - ((y / rect.height) * 100);

            // Lock lightness at 50% so saturation is visually accurate to the 2D gradient
            $ctrl.color = hslToHex(h, s, 50);
            $ctrl.displayedColorHex = $ctrl.color + Math.round($ctrl.opacity * 255).toString(16).padStart(2, '0');
            $ctrl.passBackColor();
        };

        // Called when user types in the hex input
        $ctrl.updateFromHex = function() {
            var hsl = hexToHsl($ctrl.displayedColorHex.substring(0, 7)); // Ignore alpha if present
            $ctrl.knobX = (hsl.h / 360) * $ctrl.paletteWidth;
            $ctrl.knobY = (1 - (hsl.s / 100)) * $ctrl.paletteHeight;
            $ctrl.opacity = parseInt($ctrl.color.substring(7, 9) || 'ff', 16) / 255; // Default to full opacity if not provided
            $ctrl.passBackColor();
        };

        $ctrl.updateHexFromOpacity = function() {
            $ctrl.displayedColorHex = $ctrl.color.substring(0, 8) + Math.round($ctrl.opacity * 255).toString(16).padStart(2, '0');
        }

        $ctrl.passBackColor = function() {
            if ($ctrl.updateColor) {
                $ctrl.updateColor({ colorOutput: $ctrl.displayedColorHex });
            }
        }

        // Called when user clicks a preset swatch
        $ctrl.setPreset = function(hex) {
            $ctrl.color = hex;
            $ctrl.displayedColorHex = hex + Math.round($ctrl.opacity * 255).toString(16).padStart(2, '0');
            $ctrl.updateFromHex();
        };

        $ctrl.close = function() {
            $ctrl.isOpen = false;
            console.log('A?');
            if ($ctrl.onClose) {
                $ctrl.onClose();
            }
        };
    }
});